[project]
name = "hello-aaingyunii_pr"
version = "0.1.0"
description = "The Python program I'm distributing f"
authors = [
    {name = "aaingyunii", email = "dlsrbs98@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
